const CONNECTION_STATES = Object.freeze({
  NO_FACEBOOK_LOGIN: "NO_FACEBOOK_LOGIN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  NO_PAGE: "NO_PAGE",
  PAGE_EXISTS_NO_IG: "PAGE_EXISTS_NO_IG",
  IG_PERSONAL: "IG_PERSONAL",
  PERMISSIONS_MISSING: "PERMISSIONS_MISSING",
  READY_TO_PUBLISH: "READY_TO_PUBLISH",
  RATE_LIMITED: "RATE_LIMITED",
  DETECTION_ERROR: "DETECTION_ERROR",
});

module.exports = { CONNECTION_STATES };
