const ERROR_CODES = Object.freeze({
  INTERNAL: "INTERNAL",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  DUPLICATE_RECORD: "DUPLICATE_RECORD",

  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",

  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",

  BUSINESS_INCOMPLETE: "BUSINESS_INCOMPLETE",
  BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
  BUSINESS_ALREADY_EXISTS: "BUSINESS_ALREADY_EXISTS",

  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  PLAN_UPGRADE_REQUIRED: "PLAN_UPGRADE_REQUIRED",

  UPLOAD_INVALID_MIME: "UPLOAD_INVALID_MIME",
  UPLOAD_TOO_LARGE: "UPLOAD_TOO_LARGE",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",

  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  PAYMENT_SIGNATURE_INVALID: "PAYMENT_SIGNATURE_INVALID",
  WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",

  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
});

module.exports = { ERROR_CODES };
